{
 "title": "Daily usage",
 "tags": [
  "azure-money-monitor",
  "azure-cost-insights"
 ],
 "time": { "from": "now-7d", "to": "now-2d" },
 "panels": [
  {
   "title": "Total daily usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "bill",
     "expression": {
      "from": { "property": { "name": "week", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "week\n| where $__timeFilter(UsageDateTime)\n| summarize DailyUsage=sum(PreTaxCost) by UsageDateTime",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Daily usage by resource location",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "bill",
     "query": "week\r\n| where $__timeFilter(UsageDateTime)\r\n| summarize DailyUsage=sum(PreTaxCost) by UsageDateTime, ResourceLocation"
    }
   ]
  },
  {
   "title": "Daily usage by resource type",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "database": "bill",
     "query": "week\r\n| where $__timeFilter(UsageDateTime)\r\n| summarize DailyUsage=sum(PreTaxCost) by UsageDateTime, ResourceType"
    }
   ]
  }
 ]
}