name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AzureUnitTestSubscriptionId: 'd320f99c-3d38-41c8-89d6-021f326613b8'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: f8216088-b377-492f-a834-9724b6110732
        tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47
        subscription-id: d320f99c-3d38-41c8-89d6-021f326613b8
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore src/AzureManagedGrafana.Samples.sln
    
    - name: Build
      run: dotnet build src/AzureManagedGrafana.Samples.sln --no-restore --configuration Release
    
    - name: Test
      run: dotnet test src/AzureManagedGrafana.Samples.sln --no-build --configuration Release --verbosity normal